void Menu();
int Aleatori(int NumMin, int NumMax);
void Ajuda();
void GenerarCodiOcult(int V[], int elements);
int LlegirNombre(int min, int max);
void IntToArray(int num, int V[], int elements);
void InicialitzarArray(int V[], int elements, int num);
void FrequenciaDigit(int V[],int elements,int freq[]);
int NombreEncerts(int CMaster[],int CBreaker[],int elements);
int Minim(int Valor1,int Valor2);
int NombreAproximacions(int FreqCM[],int FreqCB[],int encerts);
void ImprimirComparacions(int encerts,int aproxs);
int JocMasterMind();